### ISSUE TITLE
Edit Error (Frontend)

### ISSUE THREAD

**Issue by Warfion** [nisal-wickramage/serverlesshub-azure-functions-frontend#1]
Hello Nisal,
first of all thank you for the great project and the series in You Tube.
I managed to follow and rebuild everything so far.

Today I tried to implement the 6th step of the series.
So that means I set up the frontend - app in my Azure account.

Unfortunately, the edit - function does not work in the frontend application.

I am able to rule out an error in the Azure Function, because everything works when the APIs are accessed directly via Thunder Client.

I get the following error message in the browser console:

```
POST https://<someapplication>.azurewebsites.net/api/todoitem/4a949a6b-350e-4d55-aff3-544dfce83347 net::ERR_ABORTED 404 (Not Found)
(anonymous) @ polyfills-es2015.1ca0a42e128600892efa.js:1
C.r.<computed> @ polyfills-es2015.1ca0a42e128600892efa.js:1
(anonymous) @ main-es2015.422cd85aefc7a092af45.js:1
o @ main-es2015.422cd85aefc7a092af45.js:1
invoke @ polyfills-es2015.1ca0a42e128600892efa.js:1
onInvoke @ main-es2015.422cd85aefc7a092af45.js:1
invoke @ polyfills-es2015.1ca0a42e128600892efa.js:1
run @ polyfills-es2015.1ca0a42e128600892efa.js:1
(anonymous) @ polyfills-es2015.1ca0a42e128600892efa.js:1
invokeTask @ polyfills-es2015.1ca0a42e128600892efa.js:1
onInvokeTask @ main-es2015.422cd85aefc7a092af45.js:1
invokeTask @ polyfills-es2015.1ca0a42e128600892efa.js:1
runTask @ polyfills-es2015.1ca0a42e128600892efa.js:1
m @ polyfills-es2015.1ca0a42e128600892efa.js:1
invokeTask @ polyfills-es2015.1ca0a42e128600892efa.js:1
h @ polyfills-es2015.1ca0a42e128600892efa.js:1
p @ polyfills-es2015.1ca0a42e128600892efa.js:1

```

I use the application in version 0.1 without authentication.

Maybe you can give me a tip how to solve this problem.

Thank you very much and best regards,
Thomas

**Comment by nisal-wickramage** [comment]
Hello Thomas
Can I check if it happened after deleting an item. Because I just noticed that I haven't removed the deleted item from the list in the UI after delete icon is clicked. So if you try to edit a deleted item, the api will return 404 since the item is not in cosmos db table. Following code snippet in `EditTodoItem/index.ts` is doing so. Apologies about the UI bug. Let me know if you find the answer useful
```javascript
if(error.message.includes("Entity with the specified id does not exist in the system")){
                context.res = {
                    status:404
                };
            }
```

**Comment by Warfion** [comment]
If I create an item and delete it, then no error occurs.

Enclosed you find the short text of the error message.
```
POST https://<someapplication>.azurewebsites.net/api/todoitem/ef365eea-9864-4c2b-a7b5-cc21b18de3db net::ERR_ABORTED 404 (Not Found)
```

**Comment by Warfion** [comment]
I think I have it figured out.
In this case above a post method is called.
In my case the edit function is a get method.
I 'm going to change the edit funkction method.

**Comment by Warfion** [comment]
Now it works  :)
My fault. Sorry!
